# Generated by Django 4.2.4 on 2024-02-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_info_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(upload_to='./img', verbose_name='Photo de profil'),
        ),
    ]
