# Generated by Django 4.2.4 on 2024-02-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autheur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coor_aut', models.CharField(max_length=100, unique=True, verbose_name='Nom Prénom auteur')),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cat', models.CharField(max_length=30, unique=True, verbose_name='Code Catégorie')),
                ('lib_cat', models.CharField(max_length=70, unique=True, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='LivreBibliotheque',
            fields=[
                ('id_livre', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('descriptions', models.CharField(max_length=255, verbose_name='Description')),
                ('date_sortie', models.DateField(verbose_name='Date de sortie')),
                ('nbr_lecture', models.IntegerField(verbose_name='Nombre de lecture au total')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bibliotheque.autheur', verbose_name='Autheur')),
                ('catego', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bibliotheque.categories', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
            },
        ),
    ]
